ubi8 image upgrades
RedHatInsights/ephemeral-namespace-operator pull request #166
Opened 2023-01-31 18:53 UTC by maknop

2023-02-01 07:53 UTC, psav requested changes

2023-02-01 07:53 UTC, psav commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/go-toolset:1.18.9-8 as builder
Can we please include the timestamp versionto make it more explicit if available

2023-02-01 16:23 UTC, maknop commented
@psav and I determined that no timestamp was provided with this latest version of go-toolset.

2023-02-02 15:36 UTC, psav approved these changes

2023-02-02 15:36 UTC, merged