Ns operator tests and cleanup
RedHatInsights/ephemeral-namespace-operator pull request #69
Opened 2022-06-06 14:43 UTC by maknop

2022-06-07 15:03 UTC, BlakeHolifield approved these changes

2022-06-09 15:43 UTC, psav requested changes

2022-06-09 15:43 UTC, psav commented on apis/cloud.redhat.com/v1alpha1/namespacepool_types.go
> +	Size int `json:"size"`
A few wording updates discussed in meeting

2022-06-09 15:43 UTC, psav commented on apis/cloud.redhat.com/v1alpha1/namespacereservation_types.go
> +	Pool string `json:"pool,omitempty" default:"default"`
A few wording updates discussed in meeting

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/clowdenvironment_controller.go
> +func isOwnedBySpecificPool(ctx context.Context, cl client.Client, nsName string, uid types.UID) bool {
This will drop out in the rebase

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/namespacereservation_controller.go
> +			res.Status.Pool = res.Spec.Pool
This will also drop out in the rebase

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/namespacereservation_controller_suite_test.go
> +				nsCount := 0
Changes in here should drop out

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/namespaces.go
> +	}
Will be clobbered by rebase

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/pool_controller.go
> +	r.Log.Info(fmt.Sprintf("Populating %s", pool.Name), "ready", status["ready"], "creating", status["creating"])
Will be clobbered by rebase

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/pool_controller_suite_test.go
> +		It("Should reconcile the number of managed namespaces for each pool", func() {
Will be clobbered by rebase

2022-06-09 15:43 UTC, psav commented on controllers/cloud.redhat.com/suite_test.go
> +			Name: "default",
Will be clobbered by rebase

2022-06-09 15:43 UTC, psav commented on deploy.yml
>    value: quay.io/cloudservices/ephemeral-namespace-operator
pre-push needed

2022-06-09 16:54 UTC, psav approved these changes

2022-06-09 16:55 UTC, merged