[WIP] Add tests
RedHatInsights/ephemeral-namespace-operator pull request #92
Opened 2022-07-21 16:51 UTC by maknop

2022-07-28 18:42 UTC, bsquizz requested changes

2022-07-28 18:45 UTC, maknop commented on controllers/cloud.redhat.com/pool_controller_suite_test.go
> +						err := k8sClient.List(ctx, &secrets, client.InNamespace(ns.Name))
Ohhhh, good point. I'll update this.

2022-08-01 17:49 UTC, maknop commented on controllers/cloud.redhat.com/pool_controller_suite_test.go
> +						err := k8sClient.List(ctx, &secrets, client.InNamespace(ns.Name))
Adding this test involves more than previously thought. Something I'd like to come back to. I removed it for now.

2022-08-01 20:51 UTC, bsquizz approved these changes

2022-08-01 21:15 UTC, merged